controllers/EquiposController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Equipos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EquiposController implements the CRUD actions for Equipos model.
 */
class EquiposController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Equipos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipos model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Equipos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Equipos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->nombre]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->nombre]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Equipos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Equipos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PartidosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Partidos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PartidosController implements the CRUD actions for Partidos model.
 */
class PartidosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Partidos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Partidos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Partidos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Partidos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Partidos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Partidos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Partidos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Partidos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Partidos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Partidos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\Partidos;
use app\models\Jugadores;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionCalendario()
    {
        return $this->render('calendario');
    }
    public function actionMvp(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find() 
                ->where("nombre in (SELECT MVP FROM partidos)")
    
            ]);
        
        return $this->render("mvp",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre','edad','nombre_equipo'],
            "titulo"=>"MVPs",
            "enunciado"=>"Mvp de la temporada 2019/2020",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta2(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Yale'")
            ]);
        
        return $this->render("consulta2",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Yale",
            "enunciado"=>"Jugadores pertenecientes al centro de yale",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta3(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->select ("nombre,edad,nombre_equipo,dorsal")->where("edad >18 AND edad <25")->orderBy("edad ASC")
            ]);
        
        return $this->render("consulta3",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre','edad','nombre_equipo','dorsal'],
            "titulo"=>"Media de touchdowns",
            "enunciado"=>"Media de touchdowns",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta4(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->select ("nombre,edad,nombre_equipo,dorsal")->where("edad >18 AND edad <25")->orderBy("edad ASC")
            ]);
        
        return $this->render("consulta4",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre','edad','nombre_equipo','dorsal'],
            "titulo"=>"Jugadores mas jovenes",
            "enunciado"=>"",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta5(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->select ("nombre,edad,dorsal,centro")->where("nombre_equipo= 'Jaguar'")->orderBy("edad ASC")
            ]);
        
        return $this->render("consulta5",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre','edad','centro','dorsal'],
            "titulo"=>"Quarterbacks",
            "enunciado"=>"",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta6(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Michigan'")
            ]);
        
        return $this->render("consulta6",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Michigan",
            "enunciado"=>"Jugadores pertenecientes al centro de Michigan",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta7(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Penn State'")
            ]);
        
        return $this->render("consulta7",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Michigan",
            "enunciado"=>"Jugadores pertenecientes al centro de Penn State",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta8(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Standford'")
            ]);
        
        return $this->render("consulta8",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Standford",
            "enunciado"=>"Jugadores pertenecientes al centro de Standford",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta9(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Columbia'")
            ]);
        
        return $this->render("consulta9",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Columbia",
            "enunciado"=>"Jugadores pertenecientes al centro de Columbia",
            "sql"=>"", 
      
            
        ]);
    }
    public function actionConsulta10(){
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()
                ->where("centro = 'Clemson'")
            ]);
        
        return $this->render("consulta10",[
            "resultados"=>$dataProvider,    
            "campos"=>['nombre','edad','dorsal','posicion','nombre_equipo'],
            "titulo"=>"Centro Clemson",
            "enunciado"=>"Jugadores pertenecientes al centro de Clemson",
            "sql"=>"", 
      
            
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap" >
    <?php
    NavBar::begin([
        'brandLabel' => Html ::img('@web/nfl.png', ['alt'=>Yii::$app->name,'class'=>'logo']),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
   
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        
        'items' => [
            ['label' => 'Equipos', 'url' => ['/equipos/index']],
            ['label' => 'Jugadores', 'url' => ['/jugadores/index']],
            ['label' => 'Calendario', 'url' => ['/site/calendario']],
            ['label' => 'MVP', 'url' => ['/site/mvp']],
            ['label' => 'Centros', ['class' =>'glyphicon glyphicon-search'],
                'items' => [
                    ['label' => 'Yale', 'url' => ['/site/consulta2']],
                    ['label' => 'Michigan', 'url' => ['/site/consulta6']],
                    ['label' => 'Penn State', 'url' => ['/site/consulta7']],
                    ['label' => 'Standford', 'url' => ['/site/consulta8']],
                    ['label' => 'Columbia', 'url' => ['/site/consulta9']],
                    ['label' => 'Clemson', 'url' => ['/site/consulta10']],
                ],
            ],
            ['label' => 'Más', ['class' =>'glyphicon glyphicon-search'],
                'items' => [
                    ['label' => 'Entrenadores', 'url' => ['/entrenadores/index']],
                    ['label' => 'Personal', 'url' => ['/personal/index']],
                    ['label' => 'Partidos', 'url' => ['/partidos/index']],
                    ['label' => 'Entrenadores titulares', 'url' => ['/entrenadorespartidos/index']],
                ],
            ],
           
            //['label' => 'Nosotros', 'url' => ['/site/about']],
            //['label' => 'Contacta', 'url' => ['/site/contact']],
            
            
            /*Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )*/
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p>© <?= date('Y') ?> NFL Enterprises LLC. NFL y el diseño del escudo de la NFL son marcas registradas de la National Football League. Los nombres de los equipos, logotipos y diseños de uniformes son marcas registradas de los equipos indicados. Todas las demás marcas comerciales relacionadas con la NFL son marcas comerciales de la National Football League. Imágenes de la NFL © NFL Productions LLC.
            Términos de servicio</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>